manifest_version = 1

[module]
name = "Breadboard"
id = "breadboard"
description = "A starboard module for Breadcord. Breadboard."
version = "2.0.0"
license = "GNU GPLv3"
authors = ["Fripe"]
permissions = ["manage_webhooks"]
