[tool.ruff.lint]
select = [
    "F",        # pyflakes
    "W",        # pycodestyle warnings
    "E",        # pycodestyle errors
    "C90",      # mccabe
    "I",        # isort
    "N",        # pep8-naming
    "UP",       # pyupgrade
    "ASYNC",    # flake8-async
    "S",        # flake8-bandit
    "B",        # flake8-bugbear
    "COM",      # flake8-commas
    "C4",       # flake8-comprehensions
    "Q",        # flake8-quotes
    "RET",      # flake8-return
    "SIM",      # flake8-simplify
    "TCH",      # flake8-type-checking
    "ARG",      # flake8-unused-arguments
    "PTH",      # flake8-use-pathlib
    "PGH",      # pygrep-hooks
    "PL",       # Pylint
    "PERF",     # Perflint
    "RUF",      # Ruff-specific rules
]

ignore = [
    # Doesn't make sense for modules
    "N999",

    # I don't like this.
    "RET503",
]

[tool.ruff]
line-length = 1200


[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
